### DISCUSSION TITLE
Anyone tried to use rugby on Xcode Cloud?

### DISCUSSION THREAD

**Discussion by alvinthen** [swiftyfinch/Rugby#106] [Q&A] [answered]
Would love to know how you set it up.

I'm stuck at running rugby with this error

<img width="691" alt="image" src="https://user-images.githubusercontent.com/771989/145665272-f0e43235-67c8-403e-8f31-0fab8abd71ca.png">

Moreover, every time I push a new build, it is going to reinstall cocoapods and mint and rugby, which is pretty slow.

This is my plans.yml

```yml
- dev:
  - command: plans
    name: base

  - command: cache
    sdk: ['sim', 'ios']
    keepSources: true

- release:
  - command: plans
    name: base

  - command: cache
    sdk: ['ios']
    config: 'Release'
    bitcode: true

- base:
  - command: shell
    run: pod install
```

And my ci_post_clone.sh

```sh
#!/bin/sh

brew install cocoapods

brew install mint

mint install swiftyfinch/rugby

cd $CI_PROJECT_FILE_PATH

mint run rugby plans --plan release

```
