### DISCUSSION TITLE
Xcode 12.4 Backward Compatability

### DISCUSSION THREAD

**Discussion by devahmedshendy** [swiftyfinch/Rugby#115] [Ideas]
Hi,
This discussion following up this [comment](https://github.com/swiftyfinch/Rugby/discussions/107#discussioncomment-1988851) from @swiftyfinch to add backward compatibility for **Xcode 12.4**.

**Comment by devahmedshendy** [comment]
@swiftyfinch I made pull request for small change so Rugby installation can be supported for Xcode 12.4.
It said to make one test for this, I didn't think I should make one.

**Reply by devahmedshendy** [reply]
@swiftyfinch btw, I never learned Testing for iOS, will I need it for this project so I should add this skill too?

**Reply by swiftyfinch** [reply]
The new GitHub Actions job will be some kind of test in that case :)

**Comment by devahmedshendy** [comment]
@swiftyfinch 

For adding CI job for **Xcode 12.4** on **macOS 10.***, do you think this job is correct? (btw, this is my first time know/writing Github job:
```
rugby:
  runs-on: macos-10.0
  steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '12.4' }
    - name: Build Rugby
      run: |
        swift build -c release
        path=`swift build -c release --show-bin-path`
        echo "rugby_path=$path/rugby" >> $GITHUB_ENV
        swift run rugby --version
    - uses: actions/upload-artifact@v2
      with:
        name: rugby
        path: ${{ env.rugby_path }}
```

If so now we have two jobs with same name, what naming you suggest to distinguish both jobs reflecting their purpose?

**Reply by swiftyfinch** [reply]
@devahmedshendy Looks fine to me
Let try these?
```yml
rugby-12.5.1:
  runs-on: macos-11.0
  steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '12.5.1' }
    - name: Build Rugby
      run: |
        swift build -c release
        path=`swift build -c release --show-bin-path`
        echo "rugby_path=$path/rugby" >> $GITHUB_ENV
        swift run rugby --version
    - uses: actions/upload-artifact@v2
      with:
        name: rugby
        path: ${{ env.rugby_path }}
rugby-12.4:
  runs-on: macos-10.0
  steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '12.4' }
    - name: Build Rugby
      run: |
        swift build -c release
        path=`swift build -c release --show-bin-path`
        echo "rugby_path=$path/rugby" >> $GITHUB_ENV
        swift run rugby --version
    - uses: actions/upload-artifact@v2
      with:
        name: rugby
        path: ${{ env.rugby_path }}
```

**Reply by devahmedshendy** [reply]
Do you think we should do `upload-artifact` for different names than `rugby`? 
Can I just make separate jobs for each rugby job? so each will has its own other dependent jobs (ex: cache-both, cache-exclude, etc..)? or it is fine to run them only for `12.5.1`? Or better to re-structure this file, maybe making a separate workflow for each version?

**Reply by swiftyfinch** [reply]
Oh, I see. I think we need to remove `upload-artifacts` part.
The main goal is to check that Rugby can be built successfully with Xcode 12.4.
Something like this should be enough:
```yml
rugby-12.5.1:
  runs-on: macos-11.0
  steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '12.5.1' }
    - name: Build Rugby
      run: |
        swift build -c release
        path=`swift build -c release --show-bin-path`
        echo "rugby_path=$path/rugby" >> $GITHUB_ENV
        swift run rugby --version
    - uses: actions/upload-artifact@v2
      with:
        name: rugby
        path: ${{ env.rugby_path }}
rugby-12.4:
  runs-on: macos-10.0
  steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '12.4' }
    - name: Build Rugby
      run: swift build -c release
```

And we need to use only the last version, for example:
```yml
cache-both:
    needs: rugby-12.5.1
```
