### DISCUSSION TITLE
🎬 Installation Demo

### DISCUSSION THREAD

**Discussion by swiftyfinch** [swiftyfinch/Rugby#71] [Demo]
Hello! I've prepared 🎬 **installation Demo**. Sometimes that format is easier than text.
**Preconditions:** You need to install [Brew](https://brew.sh) 🍺 if you don't have.

## Download binary with [Homebrew](https://brew.sh) 🍺

```bash
brew tap swiftyfinch/Rugby https://github.com/swiftyfinch/Rugby.git
brew install rugby
```

## Build from source code with <a href="https://github.com/yonaskolb/Mint">Mint</a> 🌱

```bash
brew install mint
mint install swiftyfinch/rugby
```

> **Warning**: Now on **Mint 0.17.0** you'll need to add `~/.mint/bin` to your **$PATH**
> For example, add this to your `~/.zshrc` file and relaunch terminal

```bash
export PATH=$HOME/.mint/bin:$PATH
```

You can install concrete version:
```bash
mint install swiftyfinch/rugby@1.14.0
```

Dev version:
```bash
mint install swiftyfinch/rugby@main
```

## Demo Steps
1. Install [Mint](https://github.com/yonaskolb/Mint) 🌱 `brew install mint`
2. Install [Rugby](https://github.com/swiftyfinch/Rugby) 🏈 `mint install swiftyfinch/rugby`
3. Add **Rugby** 🏈 to your `$PATH`

💬 Feel free to ask any questions in this discussion.

https://user-images.githubusercontent.com/64660122/139541026-f1d0e133-aac6-4fa4-a17d-23a282059ea9.mp4

## Build from source code without any package manager (thx @alexfu)

```bash
git clone https://github.com/swiftyfinch/Rugby.git
cd Rugby
swift build -c release
cp `swift build -c release --show-bin-path`/rugby /usr/local/bin
```

## Download binary without any package manager (e.g. v1.17.3)

```bash
curl -LO https://github.com/swiftyfinch/Rugby/releases/download/1.17.3/rugby.zip
unzip rugby.zip
cp rugby/bin/rugby /usr/local/bin
```

**Comment by alexfu** [comment]
Another option, if you're not a Homebrew user, is to build from source.

```
$ git clone https://github.com/swiftyfinch/Rugby.git
$ cd Rugby
$ swift build
$ sudo cp .build/x86_64-apple-macosx/debug/rugby /usr/local/bin
```

**Reply by swiftyfinch** [reply]
@alexfu Thanks for your addition. It will be better to build the release version:

```diff
$ git clone https://github.com/swiftyfinch/Rugby.git
$ cd Rugby
- $ swift build
+ $ swift build -c release 
- $ sudo cp .build/x86_64-apple-macosx/debug/rugby /usr/local/bin
+ $ sudo cp .build/x86_64-apple-macosx/release/rugby /usr/local/bin
```

**Comment by Mattijah** [comment]
If anyone is looking for how to use/install `Rugby` on Github Actions here is a _super basic_ configuration. Any suggestions for improvements are of course welcome (_if there is a concrete thread or some kind of place for things like this let me know. I couldn't find it_). 

```yaml
- name: Cache Rugby
  id: cache-rugby
  uses: actions/cache@v3
  with:
    path: /usr/local/bin/rugby
    key: CachedRugby-default

- name: Install Rugby
  if: steps.cache-rugby.outputs.cache-hit != 'true'
  run: |
    git clone https://github.com/swiftyfinch/Rugby.git
    cd Rugby
    swift build -c release 
    sudo cp .build/x86_64-apple-macosx/release/rugby /usr/local/bin

- name: Cache Pods
  uses: actions/cache@v3
  with:
    path: |
      .rugby/build
      .rugby/cache.yml
    key: ${{ runner.os }}-CachedPods-${{ hashFiles('Podfile.lock') }}

- name: Pre-build Pods
  run: rugby
```
