### DISCUSSION TITLE
How plans.yml supports 2 configs and 2 sdks

### DISCUSSION THREAD

**Discussion by ghost** [swiftyfinch/Rugby#88] [Q&A] [answered]
Example
```
  - command: cache
    #arch: null # By default x86_64 if sdk == sim
    #config: null # By default Debug
    #sdk: sim
```
I would like cache via the following parameters but failed. 
```
config: [Debug, Release]
sdk: [ios, sim]
```

**Comment by ghost** [comment]
```
mint run rugby cache \
      --exclude Quick Nimble Nimble-Snapshots \
      --sdk sim ios \
      --config Debug Release
```
⛔️ Error: 2 unexpected arguments: 'ios', 'Release'

ref: https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md

**Reply by swiftyfinch** [reply]
Hello @Wei-Pinkoi! There are two problems:
1. I didn't release a new version with this feature: #58.
   You can find actual docs [here](https://github.com/swiftyfinch/Rugby/tree/1.13.0) for version 1.13.0;
2. Now 🏈 Rugby doesn't support an array of `configs`. You can pass only one: `rugby --config Release`

I'm going to open a new feature request in the weekend: 🚀 **Support any combinations of sdk, arch, and config**.

**Comment by ghost** [comment, marked as answer]
@swiftyfinch  

Thanks clarify. I see docs for version 1.30.0.

About you mention, is any way that cache Release config, and Debug config at the one plan on version 1.30.0? and how do I do ?

You can see `Pods/Target Support Files/AFNetworking/AFNetworking.release.xcconfig`
using the debug CONFIGURATION_BUILD_DIR.
![image](https://user-images.githubusercontent.com/93128097/143005111-e8f286f8-cf8c-4fb9-b84e-db9791375516.png)

**Reply by swiftyfinch** [reply]
Unfortunately, 🏈 Rugby hasn't single command for this.

You can try to use the version from main and use `rugby cache` twice with different configs.
But I'm not sure. And it's really inconvenient way.
As I mentioned above, I'm going to open a feature request for this.

How to install:
```shell
mint uninstall rugby
mint install swiftyfinch/rugby@main
```

`plans.yml`:
```yml
- two_configs:
  # Build for Debug 
  - command: shell
    run: pod install
  - command: cache
    config: Debug
  # Build for Release 
  - command: shell
    run: pod install
  - command: cache
    config: Release
```

**Reply by ghost** [reply]
@swiftyfinch 
Thanks. 

~Before start this feature (supporting multiple configs).
I'd like to know the issue as I mentioned(screenshot) above can be fix?
`release` confg `Pods/Target Support Files/AFNetworking/AFNetworking.release.xcconfig`
using CONFIGURATION_BUILD_DIR that value is directing the `debug` path.~

**Reply by ghost** [reply]
This plans.yml failed 
```
🌱 Finding latest version of rugby
🌱 Running rugby 1.14.0...
Plans ✈️  run
Plans ✈️  debug
Plans ✈️  base
Shell 🐚 bundle exec pod install
[4s] Shell 🐚 ✓
---------------------------------
[1s] Prepare ✓
[1s] Build ✓
[1s] Integration ✓
[1s] Clean up ✓
[1s] Cached 57/63 pods.
---------------------------------
Plans ✈️  after
Shell 🐚 echo Done
[1s] Shell 🐚 ✓
---------------------------------
Plans ✈️  release
Plans ✈️  base
Shell 🐚 bundle exec pod install
[5s] Shell 🐚 ✓
---------------------------------
Prepare Calculate checksums ✓
⛔️ Error: Couldn't find pods targets.
🚑 Try to call pod install.
🚑 Call doctor for more help: rugby doctor
```

**Reply by swiftyfinch** [reply]
Yeah, but it looks like different plan, not `two_configs`

**Reply by ghost** [reply]
Just clarify, I use this `plan.yml`
```
- two_configs:
  # Build for Debug 
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Debug
    exclude: [Quick, Nimble, Nimble-Snapshots]
  # Build for Release 
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Release
    exclude: [Quick, Nimble, Nimble-Snapshots]
```
and output is
```
🌱 Finding latest version of rugby
🌱 Running rugby 1.14.0...
Plans ✈️  two_configs
Shell 🐚 bundle exec pod install
[4s] Shell 🐚 ✓
---------------------------------
[1s] Prepare ✓
[1s] Build ✓
[1s] Integration ✓
[1s] Clean up ✓
[1s] Cached 57/63 pods.
---------------------------------
Shell 🐚 bundle exec pod install
[4s] Shell 🐚 ✓
---------------------------------
Prepare Calculate checksums ✓
⛔️ Error: Couldn't find pods targets.
🚑 Try to call pod install.
🚑 Call doctor for more help: rugby doctor
```
ref:
[build.log](https://github.com/swiftyfinch/Rugby/files/7593313/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/7593314/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/7593316/rugby.log)
[plans.txt](https://github.com/swiftyfinch/Rugby/files/7593319/plans.txt)
[cache.txt](https://github.com/swiftyfinch/Rugby/files/7593318/cache.txt)

**Reply by swiftyfinch** [reply]
Oh, I think there is a bug with saving or closing the Xcode project during all plans.
If you split plans and run them separately everything should be fine.

```yml
- a:
  # Build for Debug
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Debug
    exclude: [Quick, Nimble, Nimble-Snapshots]

- b:
  # Build for Release
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Release
    exclude: [Quick, Nimble, Nimble-Snapshots]
```

```shell
rugby --plan a ; rugby --plan b
```

**Reply by ghost** [reply]
Yes, run command separately is fine.

By the way, I checked apps for simulator. (Xcode run and show package content on ${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME})

Could you explain the reason why the bytes reduced on frameworks (14.8mb), Im interesting in!

| Cache \ Config | Debug | Release | Delta |
| :--- | ----: | ---: | ---: |
| Rugby      | 134,990,403 bytes | 108,180,756 bytes | 26,809,647 bytes |
| No cache | 149,941,619 bytes | 123,026,150 bytes | 26,915,469 bytes |
| Delta        |  -14,951,216 bytes | -14,845,394 bytes | -105,822 bytes |

**Reply by swiftyfinch** [reply]
Probably, it depends on this `xcarg`:
```yml
xcargs:
  - SWIFT_COMPILATION_MODE=wholemodule
```

**Reply by swiftyfinch** [reply]
Now it should work `rugby --plan two_configs` after that fix #90
But it is still just a workaround. I will open a new feature request.

**Comment by ghost** [comment]
Currently I use this `plan.yml` to check release train is fine.
but did not receive output from `run: echo Done`?
```
- debug:
  - command: plans
    name: base
  - command: plans
    name: cache
  - command: plans
    name: after

- release:
  - command: plans
    name: base
  - command: plans
    name: after

- base:
  - command: shell
    run: bundle exec pod install # Or you can use any shell command
    verbose: false

- cache:
  - command: cache
    sdk: [sim, ios]
    exclude: [Quick, Nimble, Nimble-Snapshots]

- after:
  - command: shell
    run: echo Done
    verbose: false
```

**Reply by ghost** [reply]
![image](https://user-images.githubusercontent.com/93128097/143167141-cc202868-6a89-449e-9309-47a602eaace9.png)

**Reply by swiftyfinch** [reply]
```yml
- after:
  - command: shell
    run: echo Done
    verbose: false # Just skip this line or use true value
```
