### ISSUE TITLE
React Native compatibility?

### ISSUE THREAD

**Issue by harryt04** [swiftyfinch/Rugby#196]
## Describe the bug
I get the following error message when I try to build my react native project after incorporating rugby into my project. Have react native projects been tested with Rugby? Everything seems to be working, but when I go to build, xcode can't find the rugby cached pods.

Do these error messages ring a bell? It seemed like the user from #117 had the same issue as me, but it wasn't clear if there was a path to resolution. I'm happy to provide more information if necessary.

```
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/AppAuth'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/CocoaAsyncSocket'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/DoubleConversion'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/FirebaseCoreDiagnostics'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/FirebaseCrashlytics'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/FirebaseInstallations'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/GoogleDataTransport'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/PromisesObjC'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/RCT-Folly.default-Futures'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/fmt'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/glog'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/libevent'
ld: warning: directory not found for option '-L/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator/nanopb'
ld: warning: directory not found for option '-F/Users/i24740/Documents/git/mobile/ios/.rugby/build/Release-iphonesimulator'
ld: library not found for -lAppAuth
```

**Comment by swiftyfinch** [comment]
Hello @harryt04!

Please, check out this comment https://github.com/swiftyfinch/Rugby/issues/136#issuecomment-1226072126. I believe it can help you. Sometimes configuration can contain different build settings and we need to support building different ones.

I see `Release` in your paths `.rugby/build/Release-iphonesimulator`. Did you pass `--config Release`? I should do it if you use scheme with `Release` config in Xcode.

**Comment by harryt04** [comment]
Yes, I noticed the same and then looked more into the advanced config with plans. I landed on this plans file and after running the xcode plan, I was able to get it to build.
```
# You can find more information here:
# https://github.com/swiftyfinch/Rugby/blob/main/Docs/Plans.md

- dev:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [x86_64]
    config: Debug
- arm:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [arm64]
    config: Debug
- ci:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [x86_64]
    config: Debug
    sdk: [ios]
- xcode:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [x86_64]
    config: Release
```


I got it building locally, but on the build server I'm currently getting this error for any package cached by rugby:
(I run the ci plan on the azure pipelines macos agent this is running on). Does this error ring a bell?
```
 Linking xrmobile

❌  ld: library not found for -lAppAuth

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/xrmobile-bfmmrocpubwipqcxwqhyzskeyhsc/Build/Products/Debug-iphoneos/xrmobile.app/xrmobile normal (in target 'xrmobile' from project 'xrmobile')
(1 failure)

```

**Comment by swiftyfinch** [comment]
Could you share command which you run? 

And do you use `pod install` before each plan?
🏈 Rugby `cache` command removes targets after build. So, unfortunately you always need to use `pod install` + `rugby cache` together.

**Comment by swiftyfinch** [comment]
And are you sure that you need to build `x86_64` for `iphoneos`? It looks strange.
May be you need to build `arm64` instead?

**Comment by harryt04** [comment]
Sure. The command I run on the build server (after installing node packages for my react native project) is: `cd ios && pod install && rugby plans --plan ci`. After this is run, I run the xcode build. It succeeds when I run it locally, but not on the build server :(

I can try arm64 and see if that helps. I don't think I've tried that yet.

**Comment by harryt04** [comment]
switching to arm64 on the build server solved my problem! Here's the final plans.yml file I landed on for anyone finding this by search later. 

```
# You can find more information here:
# https://github.com/swiftyfinch/Rugby/blob/main/Docs/Plans.md

- dev:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [x86_64]
    config: Debug
- arm:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [arm64]
    config: Debug
- ci:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [arm64]
    config: Debug
    sdk: [ios]
- xcode:
  - command: cache
    exclude: [LaunchDarkly,LDSwiftEventSource,YogaKit]
    arch: [x86_64]
    config: Release

```
