### ISSUE TITLE
ld: library not found (library search path's hash doesn't match rugby cache's hash)

### ISSUE THREAD

**Issue by PRESIDENT810** [swiftyfinch/Rugby#256]
## Describe the bug
I was integrating rugby into our CI builds so we can utilize the pod cache and make our builds faster.

However I run into some issues. Not frequent but hard to reproduce. This is an error from one of our CI build:
<img width="1287" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/c1de2af7-743d-4497-a22f-9fffd36c4e5d">

When it was building our iOS app, it aws trying to find RNReanimated library in `~/.rugby/bin/RNReanimated/Internal-iphoneos-arm64/5e5e9f6` path, and it failed. I sshed to that machine and find the only RNReanimated cache directory is `~/.rugby/bin/RNReanimated/Internal-iphoneos-arm64/1dbf35c/`.

I don't have any idea why the hash of the actual cached library's path is different with the search path. Also, when I retry the build on the same machine, it worked with the correct path.

I find this is hard to reproduce, since on CI every build clears the build directory and it's difficult to preserve the crime scene. I tried to reproduce this locally but I also can't trigger this on local builds.

I wonder why the search path's hash is different with the cache's hash? I suppose they should be generated from the same hashing mechanism?

Version: 2.1.1

**Comment by swiftyfinch** [comment]
Hello @PRESIDENT810!

Could you attach both hash files? Or you can use `diff 1dbf35c.txt 5e5e9f6.txt` by yourself.
Usually there are two issues:
1) Do you use the same Xcode version on CI? In your file `1dbf35c.txt` the last line is `swift_version: 5.7.2`. So, we need to be sure that in `5e5e9f6.txt` it will be the same.
2) Do you have some scripts in your build phases which can edit source code during building? If so, you should run all of them before Rugby. Otherwise, after build is finished the hashes will be different, because it's different source code.

**Comment by PRESIDENT810** [comment]
Hey @swiftyfinch 
The problem is I don't have 5e5e9f6.yml dumped by rugby.
<img width="493" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/aa374955-cc44-4534-bdb8-9cbca7466747">
As you can see the only cached pod is 1dbf35c. I was think of dumping two yaml file and compare the difference, too, but I didn't expect not seeing 5e5e9f6 under rugby cache directory.

I'm also pretty certain that I'm using the same Xcode version:
<img width="1305" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/bcffa986-b019-4c9d-a848-f29a42bfa50f">

<img width="1317" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/fde4918d-10d7-451c-906a-7a1fc30adc6e">

There is also no other steps between rugby cache and iOS builds:
<img width="1278" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/045848f9-011c-4031-8855-de7196eda16e">

However we do have multiple iOS builds on a same machine (both GitHub workflow and Jenkins run on the same host but different workspace, and GitHub workflow is using rugby cache while Jenkins is not), could this be a problem?

**Comment by swiftyfinch** [comment]
@PRESIDENT810 Oh, I noticed that you have absolute paths in your hash file.
```yml
- buildActionMask: 2147483647
  files:
  - '/Users/local-mobile/actions-runner/_work/mobile-app/mobile-app/node_modules/react-native-reanimated/Common/cpp/AnimatedSensor/AnimatedSensorModule.h: f2a5e39'
  - '/Users/local-mobile/actions-runner/_work/mobile-app/mobile-app/node_modules/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsProxy.h: c898f4c'
  - '/Users/local-mobile/actions-runner/_work/mobile-app/mobile-app/node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h: 81904ae'
```

It's strange and should be like this:
```yml
- buildActionMask: 2147483647
  files:
  - 'Pods/Alamofire/Source/AFError.swift: dd80e59'
  - 'Pods/Alamofire/Source/Alamofire.swift: f5b8707'
  - 'Pods/Alamofire/Source/AlamofireExtended.swift: 6b508cd'
  - 'Pods/Alamofire/Source/AuthenticationInterceptor.swift: 8b97282'
```

So, I think it's kind of bug. Rugby cuts paths relative to `Pods` directory, but you have files beyond it.
And the problem is I haven't idea how to make stable path for any machine outside of `Pods` directory. We can add project name to it, but the same binaries can't be reused between different projects.

Maybe we can try to cut relative to `Pods` at first, and if it fails, we can try again to cut relative parent directory.
