### ISSUE TITLE
🚀 Add ability to use Plans command recursively

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#68]
It will be useful to have ✈️ `Plans` command in `plans.yml`:
```yml
- base: # Preapre base plan
  - command: shell
    run: bundle
    verbose: true
  - command: shell
    run: xcodegen
    verbose: true
  - command: shell
    run: bundle exec pod install || bundle exec pod install --repo-update
    verbose: true

- dev:
  - command: plans
    run: base # And use base plan here
  - command: cache
    verbose: true
```
The syntax can be extended in the way `Makefile` works.
