### ISSUE TITLE
🐛 Update Xcode project after shell commands

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#90]
Oh, I think there is a bug with saving or closing the Xcode project during all plans.
If you split plans and run them separately everything should be fine.

```yml
- a:
  # Build for Debug
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Debug
    exclude: [Quick, Nimble, Nimble-Snapshots]

- b:
  # Build for Release
  - command: shell
    run: bundle exec pod install
  - command: cache
    config: Release
    exclude: [Quick, Nimble, Nimble-Snapshots]
```

```shell
rugby --plan a ; rugby --plan b
```

_Originally posted by @swiftyfinch in https://github.com/swiftyfinch/Rugby/discussions/88#discussioncomment-1692147_
